package com.taskmanager.controller;

import com.taskmanager.dto.BreakdownResponse;
import com.taskmanager.dto.SuggestRequest;
import com.taskmanager.dto.SummarizeResponse;
import com.taskmanager.dto.TaskRequest;
import com.taskmanager.dto.TaskResponse;
import com.taskmanager.service.TaskService;
import com.taskmanager.service.ai.AiSuggestionService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/tasks")
public class TaskController {

    private final TaskService taskService;
    private final AiSuggestionService aiSuggestionService;

    public TaskController(TaskService taskService, AiSuggestionService aiSuggestionService) {
        this.taskService = taskService;
        this.aiSuggestionService = aiSuggestionService;
    }

    // ------------------------------------------------------------------ CRUD

    /** POST /tasks — create a new task */
    @PostMapping
    public ResponseEntity<TaskResponse> create(@Valid @RequestBody TaskRequest request) {
        TaskResponse created = taskService.create(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(created);
    }

    /** GET /tasks — list all tasks */
    @GetMapping
    public ResponseEntity<List<TaskResponse>> getAll() {
        return ResponseEntity.ok(taskService.findAll());
    }

    /** GET /tasks/{id} — get a single task */
    @GetMapping("/{id}")
    public ResponseEntity<TaskResponse> getById(@PathVariable Long id) {
        return ResponseEntity.ok(taskService.findById(id));
    }

    /** PUT /tasks/{id} — replace a task */
    @PutMapping("/{id}")
    public ResponseEntity<TaskResponse> update(
            @PathVariable Long id,
            @Valid @RequestBody TaskRequest request) {
        return ResponseEntity.ok(taskService.update(id, request));
    }

    /** DELETE /tasks/{id} — delete a task */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        taskService.delete(id);
        return ResponseEntity.noContent().build();
    }

    // ------------------------------------------------------ AI summarize

    /**
     * POST /tasks/{id}/summarize
     *
     * Looks up the task (404 if missing) and returns a plain-English summary.
     * The summary is generated by the active AI provider (or the deterministic
     * mock when no API key is configured) and is never persisted.
     */
    @PostMapping("/{id}/summarize")
    public ResponseEntity<SummarizeResponse> summarize(@PathVariable Long id) {
        TaskResponse task    = taskService.findById(id);          // throws 404 if absent
        String       summary = aiSuggestionService.summarize(task);
        return ResponseEntity.ok(new SummarizeResponse(id, summary));
    }

    // ------------------------------------------------------ AI breakdown

    /**
     * POST /tasks/{id}/breakdown
     *
     * Looks up the task (404 if missing) and returns an ordered list of
     * suggested subtask descriptions.  The subtasks are never persisted;
     * the caller can choose to create individual tasks from them.
     */
    @PostMapping("/{id}/breakdown")
    public ResponseEntity<BreakdownResponse> breakdown(@PathVariable Long id) {
        TaskResponse task     = taskService.findById(id);       // throws 404 if absent
        List<String> subtasks = aiSuggestionService.breakdown(task);
        return ResponseEntity.ok(new BreakdownResponse(id, subtasks));
    }

    // -------------------------------------------------------- AI suggestion

    /**
     * POST /tasks/suggest
     *
     * Accepts: { "text": "remind me to submit the quarterly report before Friday" }
     * Returns: a structured task suggestion (not saved to the database).
     *
     * The caller can review the suggestion and then POST /tasks to save it.
     */
    @PostMapping("/suggest")
    public ResponseEntity<TaskResponse> suggest(@Valid @RequestBody SuggestRequest request) {
        TaskResponse suggestion = aiSuggestionService.suggest(request.getText());
        return ResponseEntity.ok(suggestion);
    }
}
